spring:
  cloud:
    gateway:
      routes:
        # Member Service (로컬 포트 8081)
        - id: member-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1
        
        # OAuth Kakao Service (로컬 포트 8085)
        - id: oauth-kakao-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        
        # Frontend Service (로컬 포트 5173)
        - id: frontend-service
          uri: http://localhost:5173
          predicates:
            - Path=/**
            - Path=/static/**

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값(모든 요청을 트레이싱하려면1.0)
logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에traceId, spanId추가

jwt:
  header: Authorization
  secret-key: trippickjwtsecretkey2025verysecuretrippickjwtsecretkey2025verysecure