spring:
  cloud:
    gateway:
      routes:
        # Member Service (로컬 포트 8081)
        - id: member-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1
        
        # OAuth Kakao Service (로컬 포트 8085)
        - id: oauth-kakao-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        
        # Frontend Service (로컬 포트 5173)
        - id: frontend-service
          uri: http://localhost:5173
          predicates:
            - Path=/**
            - Path=/static/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.trippick.trippick_api_gateway: DEBUG